Backend/BMW_Backend/config/routes.rb
BMWBackend::Application.routes.draw do
  resources :velocity_events

end

Backend/BMW_Backend/app/models/velocity_event.rb
class VelocityEvent < ActiveRecord::Base
end

Backend/BMW_Backend/app/controllers/velocity_events_controller.rb
class VelocityEventsController < ApplicationController
  # GET /velocity_events
  # GET /velocity_events.xml
  def index
    @velocity_events = VelocityEvent.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @velocity_events }
    end
  end

  # GET /velocity_events/1
  # GET /velocity_events/1.xml
  def show
    @velocity_event = VelocityEvent.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @velocity_event }
    end
  end

  # GET /velocity_events/new
  # GET /velocity_events/new.xml
  def new
    @velocity_event = VelocityEvent.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @velocity_event }
    end
  end

  # GET /velocity_events/1/edit
  def edit
    @velocity_event = VelocityEvent.find(params[:id])
  end

  # POST /velocity_events
  # POST /velocity_events.xml
  def create
    @velocity_event = VelocityEvent.new(params[:velocity_event])

    respond_to do |format|
      if @velocity_event.save
        format.html { redirect_to(@velocity_event, :notice => 'Velocity event was successfully created.') }
        format.xml  { render :xml => @velocity_event, :status => :created, :location => @velocity_event }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @velocity_event.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /velocity_events/1
  # PUT /velocity_events/1.xml
  def update
    @velocity_event = VelocityEvent.find(params[:id])

    respond_to do |format|
      if @velocity_event.update_attributes(params[:velocity_event])
        format.html { redirect_to(@velocity_event, :notice => 'Velocity event was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @velocity_event.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /velocity_events/1
  # DELETE /velocity_events/1.xml
  def destroy
    @velocity_event = VelocityEvent.find(params[:id])
    @velocity_event.destroy

    respond_to do |format|
      format.html { redirect_to(velocity_events_url) }
      format.xml  { head :ok }
    end
  end
end

Backend/BMW_Backend/app/helpers/velocity_events_helper.rb
module VelocityEventsHelper
end

Backend/BMW_Backend/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BMWBackend</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>

Backend/BMW_Backend/app/views/velocity_events/_form.html.erb
<%= form_for(@velocity_event) do |f| %>
  <% if @velocity_event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@velocity_event.errors.count, "error") %> prohibited this velocity_event from being saved:</h2>

      <ul>
      <% @velocity_event.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :latitude %><br />
    <%= f.text_field :latitude %>
  </div>
  <div class="field">
    <%= f.label :longitude %><br />
    <%= f.text_field :longitude %>
  </div>
  <div class="field">
    <%= f.label :velocity %><br />
    <%= f.text_field :velocity %>
  </div>
  <div class="field">
    <%= f.label :heading %><br />
    <%= f.text_field :heading %>
  </div>
  <div class="field">
    <%= f.label :device_id %><br />
    <%= f.text_field :device_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Backend/BMW_Backend/app/views/velocity_events/edit.html.erb
<h1>Editing velocity_event</h1>

<%= render 'form' %>

<%= link_to 'Show', @velocity_event %> |
<%= link_to 'Back', velocity_events_path %>

Backend/BMW_Backend/app/views/velocity_events/index.html.erb
<h1>Listing velocity_events</h1>

<table>
  <tr>
    <th>Latitude</th>
    <th>Longitude</th>
    <th>Velocity</th>
    <th>Heading</th>
    <th>Device</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @velocity_events.each do |velocity_event| %>
  <tr>
    <td><%= velocity_event.latitude %></td>
    <td><%= velocity_event.longitude %></td>
    <td><%= velocity_event.velocity %></td>
    <td><%= velocity_event.heading %></td>
    <td><%= velocity_event.device_id %></td>
    <td><%= link_to 'Show', velocity_event %></td>
    <td><%= link_to 'Edit', edit_velocity_event_path(velocity_event) %></td>
    <td><%= link_to 'Destroy', velocity_event, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Velocity event', new_velocity_event_path %>

Backend/BMW_Backend/app/views/velocity_events/new.html.erb
<h1>New velocity_event</h1>

<%= render 'form' %>

<%= link_to 'Back', velocity_events_path %>

Backend/BMW_Backend/app/views/velocity_events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Latitude:</b>
  <%= @velocity_event.latitude %>
</p>

<p>
  <b>Longitude:</b>
  <%= @velocity_event.longitude %>
</p>

<p>
  <b>Velocity:</b>
  <%= @velocity_event.velocity %>
</p>

<p>
  <b>Heading:</b>
  <%= @velocity_event.heading %>
</p>

<p>
  <b>Device:</b>
  <%= @velocity_event.device_id %>
</p>


<%= link_to 'Edit', edit_velocity_event_path(@velocity_event) %> |
<%= link_to 'Back', velocity_events_path %>